import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  const regions = await prisma.regions.createMany({
    data: [
      { region_id: 1, region_name: 'Europe' },
      { region_id: 2, region_name: 'America' },
      { region_id: 3, region_name: 'Asia' },
      { region_id: 4, region_name: 'Middle East and Africa' },
    ],
    skipDuplicates: true,
  });

  const countries = await prisma.countries.createMany({
    data: [
      { country_id: 'IT', country_name: 'Italy', region_id: 1 },
      {
        country_id: 'US',
        country_name: 'United States of America',
        region_id: 2,
      },
      { country_id: 'JP', country_name: 'Japan', region_id: 3 },
      { country_id: 'CA', country_name: 'Canada', region_id: 2 },
      { country_id: 'CN', country_name: 'China', region_id: 3 },
      { country_id: 'IN', country_name: 'India', region_id: 3 },
      { country_id: 'AU', country_name: 'Australia', region_id: 3 },
      { country_id: 'ZW', country_name: 'Zimbabwe', region_id: 4 },
      { country_id: 'SG', country_name: 'Singapore', region_id: 3 },
      { country_id: 'UK', country_name: 'United Kingdom', region_id: 1 },
      { country_id: 'FR', country_name: 'France', region_id: 1 },
      { country_id: 'DE', country_name: 'Germany', region_id: 1 },
      { country_id: 'ZM', country_name: 'Zambia', region_id: 4 },
      { country_id: 'BR', country_name: 'Brazil', region_id: 2 },
      { country_id: 'CH', country_name: 'Switzerland', region_id: 1 },
      { country_id: 'NL', country_name: 'Netherlands', region_id: 1 },
      { country_id: 'MX', country_name: 'Mexico', region_id: 2 },
      { country_id: 'KW', country_name: 'Kuwait', region_id: 4 },
      { country_id: 'IL', country_name: 'Israel', region_id: 4 },
      { country_id: 'DK', country_name: 'Denmark', region_id: 1 },
      { country_id: 'HK', country_name: 'HongKong', region_id: 3 },
      { country_id: 'NG', country_name: 'Nigeria', region_id: 4 },
      { country_id: 'AR', country_name: 'Argentina', region_id: 2 },
      { country_id: 'BE', country_name: 'Belgium', region_id: 1 },
      { country_id: 'NO', country_name: 'Norway', region_id: 1 },
      { country_id: 'EG', country_name: 'Egypt', region_id: 4 },
      { country_id: 'TN', country_name: 'Tunisia', region_id: 4 },
      { country_id: 'JM', country_name: 'Jamaica', region_id: 2 },
      { country_id: 'CL', country_name: 'Chile', region_id: 2 },
      { country_id: 'IR', country_name: 'Iran', region_id: 4 },
      { country_id: 'IQ', country_name: 'Iraq', region_id: 4 },
      { country_id: 'SY', country_name: 'Syria', region_id: 4 },
      { country_id: 'SA', country_name: 'Saudi Arabia', region_id: 4 },
      { country_id: 'YE', country_name: 'Yemen', region_id: 4 },
      { country_id: 'QA', country_name: 'Qatar', region_id: 4 },
      { country_id: 'BH', country_name: 'Bahrain', region_id: 4 },
      { country_id: 'AE', country_name: 'United Arab Emirates', region_id: 4 },
      { country_id: 'OM', country_name: 'Oman', region_id: 4 },
      { country_id: 'TR', country_name: 'Turkey', region_id: 4 },
    ],
    skipDuplicates: true,
  });

  const locations = await prisma.locations.createMany({
    data: [
      {
        location_id: 1000,
        street_address: '1297 Via Cola di Rie',
        postal_code: '00989',
        city: 'Rome',
        country_id: 'IT',
      },
      {
        location_id: 1100,
        street_address: '93091 Calle della Testa',
        postal_code: '10934',
        city: 'Venice',
        country_id: 'IT',
      },
      {
        location_id: 1200,
        street_address: '2017 Shinjuku-ku',
        postal_code: '1689',
        city: 'Tokyo',
        state_province: 'Tokyo Prefecture',
        country_id: 'JP',
      },
      {
        location_id: 1300,
        street_address: '9450 Kamiya-cho',
        postal_code: '6823',
        city: 'Hiroshima',
        country_id: 'JP',
      },
      {
        location_id: 1400,
        street_address: '2014 Jabberwocky Rd',
        postal_code: '26192',
        city: 'Southlake',
        state_province: 'Texas',
        country_id: 'US',
      },
      {
        location_id: 1500,
        street_address: '2011 Interiors Blvd',
        postal_code: '99236',
        city: 'South San Francisco',
        state_province: 'California',
        country_id: 'US',
      },
      {
        location_id: 1600,
        street_address: '2007 Zagora St',
        postal_code: '50090',
        city: 'South Brunswick',
        state_province: 'New Jersey',
        country_id: 'US',
      },
      {
        location_id: 1700,
        street_address: '2004 Charade Rd',
        postal_code: '98199',
        city: 'Seattle',
        state_province: 'Washington',
        country_id: 'US',
      },
      {
        location_id: 1800,
        street_address: '147 Spadina Ave',
        postal_code: 'M5V 2L7',
        city: 'Toronto',
        state_province: 'Ontario',
        country_id: 'CA',
      },
      {
        location_id: 1900,
        street_address: '6092 Boxwood St',
        postal_code: 'YSW 9T2',
        city: 'Whitehorse',
        state_province: 'Yukon',
        country_id: 'CA',
      },
      {
        location_id: 2000,
        street_address: '40-5-12 Laogianggen',
        postal_code: '190518',
        city: 'Beijing',
        country_id: 'CN',
      },
      {
        location_id: 2100,
        street_address: '1298 Vileparle (E)',
        postal_code: '490231',
        city: 'Bombay',
        state_province: 'Maharashtra',
        country_id: 'IN',
      },
      {
        location_id: 2200,
        street_address: '12-98 Victoria Street',
        postal_code: '2901',
        city: 'Sydney',
        state_province: 'New South Wales',
        country_id: 'AU',
      },
      {
        location_id: 2300,
        street_address: '198 Clementi North',
        postal_code: '540198',
        city: 'Singapore',
        country_id: 'SG',
      },
      {
        location_id: 2400,
        street_address: '8204 Arthur St',
        postal_code: 'Y9722',
        city: 'London',
        country_id: 'UK',
      },
      {
        location_id: 2500,
        street_address: 'Magdalen Centre, The Oxford Science Park',
        postal_code: 'OX9 9ZB',
        city: 'Oxford',
        state_province: 'Oxford',
        country_id: 'UK',
      },
      {
        location_id: 2600,
        street_address: '9702 Chester Road',
        postal_code: '962985015',
        city: 'Stretford',
        state_province: 'Manchester',
        country_id: 'UK',
      },
      {
        location_id: 2700,
        street_address: 'Schwanthalerstr. 7031',
        postal_code: '80925',
        city: 'Munich',
        state_province: 'Bavaria',
        country_id: 'DE',
      },
      {
        location_id: 2800,
        street_address: 'Rua Frei Caneca 1360',
        postal_code: '01307-002',
        city: 'Sao Paulo',
        state_province: 'Sao Paulo',
        country_id: 'BR',
      },
      {
        location_id: 2900,
        street_address: '20 Rue des Corps-Saints',
        postal_code: '1730',
        city: 'Geneva',
        state_province: 'Geneve',
        country_id: 'CH',
      },
      {
        location_id: 3000,
        street_address: 'Murtenstrasse 921',
        postal_code: '3095',
        city: 'Bern',
        state_province: 'BE',
        country_id: 'CH',
      },
      {
        location_id: 3100,
        street_address: 'Pieter Breughelstraat 837',
        postal_code: '3029SK',
        city: 'Utrecht',
        state_province: 'Utrecht',
        country_id: 'NL',
      },
      {
        location_id: 3200,
        street_address: 'Mariano Escobedo 9991',
        postal_code: '11932',
        city: 'Mexico City',
        state_province: 'Distrito Federal,',
        country_id: 'MX',
      },
    ],
    skipDuplicates: true,
  });

  const jobs = await prisma.jobs.createMany({
    data: [
      {
        job_id: 'AD_PRES',
        job_title: 'President',
        min_salary: 20000,
        max_salary: 40000,
      },
      {
        job_id: 'AD_VP',
        job_title: 'Administration Vice President',
        min_salary: 15000,
        max_salary: 30000,
      },
      {
        job_id: 'AD_ASST',
        job_title: 'Administration Assistant',
        min_salary: 3000,
        max_salary: 6000,
      },
      {
        job_id: 'AC_MGR',
        job_title: 'Accounting Manager',
        min_salary: 8200,
        max_salary: 16000,
      },
      {
        job_id: 'AC_ACCOUNT',
        job_title: 'Public Accountant',
        min_salary: 4200,
        max_salary: 9000,
      },
      {
        job_id: 'SA_MAN',
        job_title: 'Sales Manager',
        min_salary: 10000,
        max_salary: 20000,
      },
      {
        job_id: 'SA_REP',
        job_title: 'Sales Representative',
        min_salary: 6000,
        max_salary: 12000,
      },
      {
        job_id: 'PU_MAN',
        job_title: 'Purchasing Manager',
        min_salary: 8000,
        max_salary: 15000,
      },
      {
        job_id: 'PU_CLERK',
        job_title: 'Purchasing Clerk',
        min_salary: 2500,
        max_salary: 5500,
      },
      {
        job_id: 'ST_MAN',
        job_title: 'Stock Manager',
        min_salary: 5500,
        max_salary: 8500,
      },
      {
        job_id: 'ST_CLERK',
        job_title: 'Stock Clerk',
        min_salary: 2000,
        max_salary: 5000,
      },
      {
        job_id: 'SH_CLERK',
        job_title: 'Shipping Clerk',
        min_salary: 2500,
        max_salary: 5500,
      },
      {
        job_id: 'IT_PROG',
        job_title: 'Programmer',
        min_salary: 4000,
        max_salary: 10000,
      },
      {
        job_id: 'MK_MAN',
        job_title: 'Marketing Manager',
        min_salary: 9000,
        max_salary: 15000,
      },
      {
        job_id: 'MK_REP',
        job_title: 'Marketing Representative',
        min_salary: 4000,
        max_salary: 9000,
      },
      {
        job_id: 'HR_REP',
        job_title: 'Human Resources Representative',
        min_salary: 4000,
        max_salary: 9000,
      },
      {
        job_id: 'PR_REP',
        job_title: 'Public Relations Representative',
        min_salary: 4500,
        max_salary: 10500,
      },
      {
        job_id: 'FI_MGR',
        job_title: 'Finance Manager',
        min_salary: 8200,
        max_salary: 16000,
      },
      {
        job_id: 'FI_ACCOUNT',
        job_title: 'Accountant',
        min_salary: 4200,
        max_salary: 9000,
      },
    ],
    skipDuplicates: true,
  });

  const departments = await prisma.departments.createMany({
    data: [
      {
        department_id: 10,
        department_name: 'Administration',
        location_id: 1700,
      },
      { department_id: 20, department_name: 'Marketing', location_id: 1800 },
      { department_id: 30, department_name: 'Purchasing', location_id: 1700 },
      {
        department_id: 40,
        department_name: 'Human Resources',
        location_id: 2400,
      },
      { department_id: 50, department_name: 'Shipping', location_id: 1500 },
      { department_id: 60, department_name: 'IT', location_id: 1400 },
      {
        department_id: 70,
        department_name: 'Public Relations',
        location_id: 2700,
      },
      { department_id: 80, department_name: 'Sales', location_id: 2500 },
      { department_id: 90, department_name: 'Executive', location_id: 1700 },
      { department_id: 100, department_name: 'Finance', location_id: 1700 },
      { department_id: 110, department_name: 'Accounting', location_id: 1700 },
      { department_id: 120, department_name: 'Treasury', location_id: 1700 },
      {
        department_id: 130,
        department_name: 'Corporate Tax',
        location_id: 1700,
      },
      {
        department_id: 140,
        department_name: 'Control And Credit',
        location_id: 1700,
      },
      {
        department_id: 150,
        department_name: 'Shareholder Services',
        location_id: 1700,
      },
      { department_id: 160, department_name: 'Benefits', location_id: 1700 },
      {
        department_id: 170,
        department_name: 'Manufacturing',
        location_id: 1700,
      },
      {
        department_id: 180,
        department_name: 'Construction',
        location_id: 1700,
      },
      { department_id: 190, department_name: 'Contracting', location_id: 1700 },
      { department_id: 200, department_name: 'Operations', location_id: 1700 },
      { department_id: 210, department_name: 'IT Support', location_id: 1700 },
      { department_id: 220, department_name: 'NOC', location_id: 1700 },
      { department_id: 230, department_name: 'IT Helpdesk', location_id: 1700 },
      {
        department_id: 240,
        department_name: 'Government Sales',
        location_id: 1700,
      },
      {
        department_id: 250,
        department_name: 'Retail Sales',
        location_id: 1700,
      },
      { department_id: 260, department_name: 'Recruiting', location_id: 1700 },
      { department_id: 270, department_name: 'Payroll', location_id: 1700 },
    ],
    skipDuplicates: true,
  });

  const employees = await prisma.employees.createMany({
    data: [
      {
        employee_id: 100,
        first_name: 'Steven',
        last_name: 'King',
        email: 'steven.king@prisma.io',
        phone_number: '515.123.4567',
        hire_date: new Date('1987-06-17'),
        job_id: 'AD_PRES',
        salary: 24000,
        department_id: 90,
      },
      {
        employee_id: 101,
        first_name: 'Neena',
        last_name: 'Kochhar',
        email: 'neena.kochhar@prisma.io',
        phone_number: '515.123.4568',
        hire_date: new Date('1989-09-21'),
        job_id: 'AD_VP',
        salary: 17000,
        manager_id: 100,
        department_id: 90,
      },
      {
        employee_id: 102,
        first_name: 'Lex',
        last_name: 'De Haan',
        email: 'lex.dehaan@prisma.io',
        phone_number: '515.123.4569',
        hire_date: new Date('1993-01-13'),
        job_id: 'AD_VP',
        salary: 17000,
        manager_id: 100,
        department_id: 90,
      },
      {
        employee_id: 103,
        first_name: 'Alexander',
        last_name: 'Hunold',
        email: 'alexander.hunold@prisma.io',
        phone_number: '590.423.4567',
        hire_date: new Date('1990-01-03'),
        job_id: 'IT_PROG',
        salary: 9000,
        manager_id: 102,
        department_id: 60,
      },
      {
        employee_id: 104,
        first_name: 'Bruce',
        last_name: 'Ernst',
        email: 'bruce.ernst@prisma.io',
        phone_number: '590.423.4568',
        hire_date: new Date('1991-05-21'),
        job_id: 'IT_PROG',
        salary: 6000,
        manager_id: 103,
        department_id: 60,
      },
      {
        employee_id: 105,
        first_name: 'David',
        last_name: 'Austin',
        email: 'david.austin@prisma.io',
        phone_number: '590.423.4569',
        hire_date: new Date('1997-06-25'),
        job_id: 'IT_PROG',
        salary: 4800,
        manager_id: 103,
        department_id: 60,
      },
      {
        employee_id: 106,
        first_name: 'Valli',
        last_name: 'Pataballa',
        email: 'valli.pataballa@prisma.io',
        phone_number: '590.423.4560',
        hire_date: new Date('1998-02-05'),
        job_id: 'IT_PROG',
        salary: 4800,
        manager_id: 103,
        department_id: 60,
      },
      {
        employee_id: 107,
        first_name: 'Diana',
        last_name: 'Lorentz',
        email: 'diana.lorentz@prisma.io',
        phone_number: '590.423.5567',
        hire_date: new Date('1999-02-07'),
        job_id: 'IT_PROG',
        salary: 4200,
        manager_id: 103,
        department_id: 60,
      },
      {
        employee_id: 108,
        first_name: 'Nancy',
        last_name: 'Greenberg',
        email: 'nancy.greenberg@prisma.io',
        phone_number: '515.124.4569',
        hire_date: new Date('1994-08-17'),
        job_id: 'FI_MGR',
        salary: 12000,
        manager_id: 101,
        department_id: 100,
      },
      {
        employee_id: 109,
        first_name: 'Daniel',
        last_name: 'Faviet',
        email: 'daniel.faviet@prisma.io',
        phone_number: '515.124.4169',
        hire_date: new Date('1994-08-16'),
        job_id: 'FI_ACCOUNT',
        salary: 9000,
        manager_id: 108,
        department_id: 100,
      },
      {
        employee_id: 110,
        first_name: 'John',
        last_name: 'Chen',
        email: 'john.chen@prisma.io',
        phone_number: '515.124.4269',
        hire_date: new Date('1997-09-28'),
        job_id: 'FI_ACCOUNT',
        salary: 8200,
        manager_id: 108,
        department_id: 100,
      },
      {
        employee_id: 111,
        first_name: 'Ismael',
        last_name: 'Sciarra',
        email: 'ismael.sciarra@prisma.io',
        phone_number: '515.124.4369',
        hire_date: new Date('1997-09-30'),
        job_id: 'FI_ACCOUNT',
        salary: 7700,
        manager_id: 108,
        department_id: 100,
      },
      {
        employee_id: 112,
        first_name: 'Jose Manuel',
        last_name: 'Urman',
        email: 'josemanuel.urman@prisma.io',
        phone_number: '515.124.4469',
        hire_date: new Date('1998-03-07'),
        job_id: 'FI_ACCOUNT',
        salary: 7800,
        manager_id: 108,
        department_id: 100,
      },
      {
        employee_id: 113,
        first_name: 'Luis',
        last_name: 'Popp',
        email: 'luis.popp@prisma.io',
        phone_number: '515.124.4567',
        hire_date: new Date('1999-12-07'),
        job_id: 'FI_ACCOUNT',
        salary: 6900,
        manager_id: 108,
        department_id: 100,
      },
      {
        employee_id: 114,
        first_name: 'Den',
        last_name: 'Raphaely',
        email: 'den.raphaely@prisma.io',
        phone_number: '515.127.4561',
        hire_date: new Date('1994-12-07'),
        job_id: 'PU_MAN',
        salary: 11000,
        manager_id: 100,
        department_id: 30,
      },
      {
        employee_id: 115,
        first_name: 'Alexander',
        last_name: 'Khoo',
        email: 'alexander.khoo@prisma.io',
        phone_number: '515.127.4562',
        hire_date: new Date('1995-05-18'),
        job_id: 'PU_CLERK',
        salary: 3100,
        manager_id: 114,
        department_id: 30,
      },
      {
        employee_id: 116,
        first_name: 'Shelli',
        last_name: 'Baida',
        email: 'shelli.baida@prisma.io',
        phone_number: '515.127.4563',
        hire_date: new Date('1997-12-24'),
        job_id: 'PU_CLERK',
        salary: 2900,
        manager_id: 114,
        department_id: 30,
      },
      {
        employee_id: 117,
        first_name: 'Sigal',
        last_name: 'Tobias',
        email: 'sigal.tobias@prisma.io',
        phone_number: '515.127.4564',
        hire_date: new Date('1997-07-24'),
        job_id: 'PU_CLERK',
        salary: 2800,
        manager_id: 114,
        department_id: 30,
      },
      {
        employee_id: 118,
        first_name: 'Guy',
        last_name: 'Himuro',
        email: 'guy.himuro@prisma.io',
        phone_number: '515.127.4565',
        hire_date: new Date('1998-11-15'),
        job_id: 'PU_CLERK',
        salary: 2600,
        manager_id: 114,
        department_id: 30,
      },
      {
        employee_id: 119,
        first_name: 'Karen',
        last_name: 'Colmenares',
        email: 'karen.colmenares@prisma.io',
        phone_number: '515.127.4566',
        hire_date: new Date('1999-08-10'),
        job_id: 'PU_CLERK',
        salary: 2500,
        manager_id: 114,
        department_id: 30,
      },
      {
        employee_id: 120,
        first_name: 'Matthew',
        last_name: 'Weiss',
        email: 'matthew.weiss@prisma.io',
        phone_number: '650.123.1234',
        hire_date: new Date('1996-07-18'),
        job_id: 'ST_MAN',
        salary: 8000,
        manager_id: 100,
        department_id: 50,
      },
      {
        employee_id: 121,
        first_name: 'Adam',
        last_name: 'Fripp',
        email: 'adam.fripp@prisma.io',
        phone_number: '650.123.2234',
        hire_date: new Date('1997-04-10'),
        job_id: 'ST_MAN',
        salary: 8200,
        manager_id: 100,
        department_id: 50,
      },
      {
        employee_id: 122,
        first_name: 'Payam',
        last_name: 'Kaufling',
        email: 'payam.kaufling@prisma.io',
        phone_number: '650.123.3234',
        hire_date: new Date('1995-05-01'),
        job_id: 'ST_MAN',
        salary: 7900,
        manager_id: 100,
        department_id: 50,
      },
      {
        employee_id: 123,
        first_name: 'Shanta',
        last_name: 'Vollman',
        email: 'shanta.vollman@prisma.io',
        phone_number: '650.123.4234',
        hire_date: new Date('1997-10-10'),
        job_id: 'ST_MAN',
        salary: 6500,
        manager_id: 100,
        department_id: 50,
      },
      {
        employee_id: 124,
        first_name: 'Kevin',
        last_name: 'Mourgos',
        email: 'kevin.mourgos@prisma.io',
        phone_number: '650.123.5234',
        hire_date: new Date('1999-11-16'),
        job_id: 'ST_MAN',
        salary: 5800,
        manager_id: 100,
        department_id: 50,
      },
      {
        employee_id: 125,
        first_name: 'Julia',
        last_name: 'Nayer',
        email: 'julia.nayer@prisma.io',
        phone_number: '650.124.1214',
        hire_date: new Date('1997-07-16'),
        job_id: 'ST_CLERK',
        salary: 3200,
        manager_id: 120,
        department_id: 50,
      },
      {
        employee_id: 126,
        first_name: 'Irene',
        last_name: 'Mikkilineni',
        email: 'irene.mikkilineni@prisma.io',
        phone_number: '650.124.1224',
        hire_date: new Date('1998-09-28'),
        job_id: 'ST_CLERK',
        salary: 2700,
        manager_id: 120,
        department_id: 50,
      },
      {
        employee_id: 127,
        first_name: 'James',
        last_name: 'Landry',
        email: 'james.landry@prisma.io',
        phone_number: '650.124.1334',
        hire_date: new Date('1999-01-14'),
        job_id: 'ST_CLERK',
        salary: 2400,
        manager_id: 120,
        department_id: 50,
      },
      {
        employee_id: 128,
        first_name: 'Steven',
        last_name: 'Markle',
        email: 'steven.markle@prisma.io',
        phone_number: '650.124.1434',
        hire_date: new Date('2000-03-08'),
        job_id: 'ST_CLERK',
        salary: 2200,
        manager_id: 120,
        department_id: 50,
      },
      {
        employee_id: 129,
        first_name: 'Laura',
        last_name: 'Bissot',
        email: 'laura.bissot@prisma.io',
        phone_number: '650.124.5234',
        hire_date: new Date('1997-08-20'),
        job_id: 'ST_CLERK',
        salary: 3300,
        manager_id: 121,
        department_id: 50,
      },
      {
        employee_id: 130,
        first_name: 'Mozhe',
        last_name: 'Atkinson',
        email: 'mozhe.atkinson@prisma.io',
        phone_number: '650.124.6234',
        hire_date: new Date('1997-10-30'),
        job_id: 'ST_CLERK',
        salary: 2800,
        manager_id: 121,
        department_id: 50,
      },
      {
        employee_id: 131,
        first_name: 'James',
        last_name: 'Marlow',
        email: 'james.marlow@prisma.io',
        phone_number: '650.124.7234',
        hire_date: new Date('1998-02-16'),
        job_id: 'ST_CLERK',
        salary: 2500,
        manager_id: 121,
        department_id: 50,
      },
      {
        employee_id: 132,
        first_name: 'TJ',
        last_name: 'Olson',
        email: 'tj.olson@prisma.io',
        phone_number: '650.124.8234',
        hire_date: new Date('1998-04-10'),
        job_id: 'ST_CLERK',
        salary: 2100,
        manager_id: 121,
        department_id: 50,
      },
      {
        employee_id: 133,
        first_name: 'Jason',
        last_name: 'Mallin',
        email: 'jason.mallin@prisma.io',
        phone_number: '650.127.1934',
        hire_date: new Date('1996-06-14'),
        job_id: 'ST_CLERK',
        salary: 3300,
        manager_id: 122,
        department_id: 50,
      },
      {
        employee_id: 134,
        first_name: 'Michael',
        last_name: 'Rogers',
        email: 'michael.rogers@prisma.io',
        phone_number: '650.127.1834',
        hire_date: new Date('1998-08-26'),
        job_id: 'ST_CLERK',
        salary: 2900,
        manager_id: 122,
        department_id: 50,
      },
      {
        employee_id: 135,
        first_name: 'Ki',
        last_name: 'Gee',
        email: 'ki.gee@prisma.io',
        phone_number: '650.127.1734',
        hire_date: new Date('1999-12-12'),
        job_id: 'ST_CLERK',
        salary: 2400,
        manager_id: 122,
        department_id: 50,
      },
      {
        employee_id: 136,
        first_name: 'Hazel',
        last_name: 'Philtanker',
        email: 'hazel.philtanker@prisma.io',
        phone_number: '650.127.1634',
        hire_date: new Date('2000-02-06'),
        job_id: 'ST_CLERK',
        salary: 2200,
        manager_id: 122,
        department_id: 50,
      },
      {
        employee_id: 137,
        first_name: 'Renske',
        last_name: 'Ladwig',
        email: 'renske.ladwig@prisma.io',
        phone_number: '650.121.1234',
        hire_date: new Date('1994-07-14'),
        job_id: 'ST_CLERK',
        salary: 3600,
        manager_id: 123,
        department_id: 50,
      },
      {
        employee_id: 138,
        first_name: 'Stephen',
        last_name: 'Stiles',
        email: 'stephen.stiles@prisma.io',
        phone_number: '650.121.2034',
        hire_date: new Date('1997-10-26'),
        job_id: 'ST_CLERK',
        salary: 3200,
        manager_id: 123,
        department_id: 50,
      },
      {
        employee_id: 139,
        first_name: 'John',
        last_name: 'Seo',
        email: 'john.seo@prisma.io',
        phone_number: '650.121.2019',
        hire_date: new Date('1998-02-12'),
        job_id: 'ST_CLERK',
        salary: 2700,
        manager_id: 123,
        department_id: 50,
      },
      {
        employee_id: 140,
        first_name: 'Joshua',
        last_name: 'Patel',
        email: 'joshua.patel@prisma.io',
        phone_number: '650.121.1834',
        hire_date: new Date('1999-04-06'),
        job_id: 'ST_CLERK',
        salary: 2500,
        manager_id: 123,
        department_id: 50,
      },
      {
        employee_id: 141,
        first_name: 'Trenna',
        last_name: 'Rajs',
        email: 'trenna.rajs@prisma.io',
        phone_number: '650.121.8009',
        hire_date: new Date('1995-10-17'),
        job_id: 'ST_CLERK',
        salary: 3500,
        manager_id: 124,
        department_id: 50,
      },
      {
        employee_id: 142,
        first_name: 'Curtis',
        last_name: 'Davies',
        email: 'curtis.davies@prisma.io',
        phone_number: '650.121.2994',
        hire_date: new Date('1997-01-29'),
        job_id: 'ST_CLERK',
        salary: 3100,
        manager_id: 124,
        department_id: 50,
      },
      {
        employee_id: 143,
        first_name: 'Randall',
        last_name: 'Matos',
        email: 'randall.matos@prisma.io',
        phone_number: '650.121.2874',
        hire_date: new Date('1998-03-15'),
        job_id: 'ST_CLERK',
        salary: 2600,
        manager_id: 124,
        department_id: 50,
      },
      {
        employee_id: 144,
        first_name: 'Peter',
        last_name: 'Vargas',
        email: 'peter.vargas@prisma.io',
        phone_number: '650.121.2004',
        hire_date: new Date('1998-07-09'),
        job_id: 'ST_CLERK',
        salary: 2500,
        manager_id: 124,
        department_id: 50,
      },
      {
        employee_id: 145,
        first_name: 'John',
        last_name: 'Russell',
        email: 'john.russell@prisma.io',
        phone_number: '011.44.1344.429268',
        hire_date: new Date('1996-10-01'),
        job_id: 'SA_MAN',
        salary: 14000,
        commission_pct: 0.4,
        manager_id: 100,
        department_id: 80,
      },
      {
        employee_id: 146,
        first_name: 'Karen',
        last_name: 'Partners',
        email: 'karen.partners@prisma.io',
        phone_number: '011.44.1344.467268',
        hire_date: new Date('1997-01-05'),
        job_id: 'SA_MAN',
        salary: 13500,
        commission_pct: 0.3,
        manager_id: 100,
        department_id: 80,
      },
      {
        employee_id: 147,
        first_name: 'Alberto',
        last_name: 'Errazuriz',
        email: 'alberto.errazuriz@prisma.io',
        phone_number: '011.44.1344.429278',
        hire_date: new Date('1999-03-10'),
        job_id: 'SA_MAN',
        salary: 12000,
        commission_pct: 0.3,
        manager_id: 100,
        department_id: 80,
      },
      {
        employee_id: 148,
        first_name: 'Gerald',
        last_name: 'Cambrault',
        email: 'gerald.cambrault@prisma.io',
        phone_number: '011.44.1344.619268',
        hire_date: new Date('1997-10-15'),
        job_id: 'SA_MAN',
        salary: 11000,
        commission_pct: 0.3,
        manager_id: 100,
        department_id: 80,
      },
      {
        employee_id: 149,
        first_name: 'Eleni',
        last_name: 'Zlotkey',
        email: 'eleni.zlotkey@prisma.io',
        phone_number: '011.44.1344.429018',
        hire_date: new Date('1998-01-29'),
        job_id: 'SA_MAN',
        salary: 10500,
        commission_pct: 0.2,
        manager_id: 100,
        department_id: 80,
      },
      {
        employee_id: 150,
        first_name: 'Peter',
        last_name: 'Tucker',
        email: 'peter.tucker@prisma.io',
        phone_number: '011.44.1344.129268',
        hire_date: new Date('1997-01-30'),
        job_id: 'SA_REP',
        salary: 10000,
        commission_pct: 0.3,
        manager_id: 145,
        department_id: 80,
      },
      {
        employee_id: 151,
        first_name: 'David',
        last_name: 'Bernstein',
        email: 'david.bernstein@prisma.io',
        phone_number: '011.44.1344.345268',
        hire_date: new Date('1997-03-24'),
        job_id: 'SA_REP',
        salary: 9500,
        commission_pct: 0.25,
        manager_id: 145,
        department_id: 80,
      },
      {
        employee_id: 152,
        first_name: 'Peter',
        last_name: 'Hall',
        email: 'peter.hall@prisma.io',
        phone_number: '011.44.1345.829268',
        hire_date: new Date('1996-08-20'),
        job_id: 'SA_REP',
        salary: 9000,
        commission_pct: 0.25,
        manager_id: 145,
        department_id: 80,
      },
      {
        employee_id: 153,
        first_name: 'Christopher',
        last_name: 'Olsen',
        email: 'christopher.olsen@prisma.io',
        phone_number: '011.44.1343.929268',
        hire_date: new Date('1997-03-30'),
        job_id: 'SA_REP',
        salary: 8000,
        commission_pct: 0.2,
        manager_id: 145,
        department_id: 80,
      },
      {
        employee_id: 154,
        first_name: 'Nanette',
        last_name: 'Cambrault',
        email: 'nanette.cambrault@prisma.io',
        phone_number: '011.44.1343.529268',
        hire_date: new Date('1998-12-09'),
        job_id: 'SA_REP',
        salary: 7500,
        commission_pct: 0.2,
        manager_id: 145,
        department_id: 80,
      },
      {
        employee_id: 155,
        first_name: 'Oliver',
        last_name: 'Tuvault',
        email: 'oliver.tuvault@prisma.io',
        phone_number: '011.44.1343.929268',
        hire_date: new Date('1999-11-23'),
        job_id: 'SA_REP',
        salary: 7000,
        commission_pct: 0.15,
        manager_id: 145,
        department_id: 80,
      },
      {
        employee_id: 156,
        first_name: 'Janette',
        last_name: 'King',
        email: 'janette.king@prisma.io',
        phone_number: '011.44.1345.429268',
        hire_date: new Date('2000-01-30'),
        job_id: 'SA_REP',
        salary: 10000,
        commission_pct: 0.35,
        manager_id: 146,
        department_id: 80,
      },
      {
        employee_id: 157,
        first_name: 'Patrick',
        last_name: 'Sully',
        email: 'patrick.sully@prisma.io',
        phone_number: '011.44.1345.929268',
        hire_date: new Date('1996-03-04'),
        job_id: 'SA_REP',
        salary: 9500,
        commission_pct: 0.35,
        manager_id: 146,
        department_id: 80,
      },
      {
        employee_id: 158,
        first_name: 'Allan',
        last_name: 'McEwen',
        email: 'allan.mcewen@prisma.io',
        phone_number: '011.44.1345.829268',
        hire_date: new Date('1997-08-01'),
        job_id: 'SA_REP',
        salary: 9000,
        commission_pct: 0.35,
        manager_id: 146,
        department_id: 80,
      },
      {
        employee_id: 159,
        first_name: 'Lindsey',
        last_name: 'Smith',
        email: 'lindsey.smith@prisma.io',
        phone_number: '011.44.1345.729268',
        hire_date: new Date('1997-03-10'),
        job_id: 'SA_REP',
        salary: 8000,
        commission_pct: 0.3,
        manager_id: 146,
        department_id: 80,
      },
      {
        employee_id: 160,
        first_name: 'Louise',
        last_name: 'Doran',
        email: 'louise.doran@prisma.io',
        phone_number: '011.44.1345.629268',
        hire_date: new Date('1998-12-15'),
        job_id: 'SA_REP',
        salary: 7500,
        commission_pct: 0.3,
        manager_id: 146,
        department_id: 80,
      },
      {
        employee_id: 161,
        first_name: 'Sarath',
        last_name: 'Sewall',
        email: 'sarath.sewall@prisma.io',
        phone_number: '011.44.1345.529268',
        hire_date: new Date('1999-11-03'),
        job_id: 'SA_REP',
        salary: 7000,
        commission_pct: 0.25,
        manager_id: 146,
        department_id: 80,
      },
      {
        employee_id: 162,
        first_name: 'Clara',
        last_name: 'Vishney',
        email: 'clara.vishney@prisma.io',
        phone_number: '011.44.1346.129268',
        hire_date: new Date('1997-11-11'),
        job_id: 'SA_REP',
        salary: 10500,
        commission_pct: 0.25,
        manager_id: 147,
        department_id: 80,
      },
      {
        employee_id: 163,
        first_name: 'Danielle',
        last_name: 'Greene',
        email: 'danielle.greene@prisma.io',
        phone_number: '011.44.1346.229268',
        hire_date: new Date('1999-03-19'),
        job_id: 'SA_REP',
        salary: 9500,
        commission_pct: 0.15,
        manager_id: 147,
        department_id: 80,
      },
      {
        employee_id: 164,
        first_name: 'Mattea',
        last_name: 'Marvins',
        email: 'mattea.marvins@prisma.io',
        phone_number: '011.44.1346.329268',
        hire_date: new Date('2000-01-24'),
        job_id: 'SA_REP',
        salary: 7200,
        commission_pct: 0.1,
        manager_id: 147,
        department_id: 80,
      },
      {
        employee_id: 165,
        first_name: 'David',
        last_name: 'Lee',
        email: 'david.lee@prisma.io',
        phone_number: '011.44.1346.529268',
        hire_date: new Date('1997-02-23'),
        job_id: 'SA_REP',
        salary: 6800,
        commission_pct: 0.1,
        manager_id: 147,
        department_id: 80,
      },
      {
        employee_id: 166,
        first_name: 'Sundar',
        last_name: 'Ande',
        email: 'sundar.ande@prisma.io',
        phone_number: '011.44.1346.629268',
        hire_date: new Date('2000-03-24'),
        job_id: 'SA_REP',
        salary: 6400,
        commission_pct: 0.1,
        manager_id: 147,
        department_id: 80,
      },
      {
        employee_id: 167,
        first_name: 'Amit',
        last_name: 'Banda',
        email: 'amit.banda@prisma.io',
        phone_number: '011.44.1346.729268',
        hire_date: new Date('1996-04-21'),
        job_id: 'SA_REP',
        salary: 6200,
        commission_pct: 0.1,
        manager_id: 147,
        department_id: 80,
      },
      {
        employee_id: 168,
        first_name: 'Lisa',
        last_name: 'Ozer',
        email: 'lisa.ozer@prisma.io',
        phone_number: '011.44.1343.929268',
        hire_date: new Date('1997-03-11'),
        job_id: 'SA_REP',
        salary: 11500,
        commission_pct: 0.25,
        manager_id: 148,
        department_id: 80,
      },
      {
        employee_id: 169,
        first_name: 'Harrison',
        last_name: 'Bloom',
        email: 'harrison.bloom@prisma.io',
        phone_number: '011.44.1343.829268',
        hire_date: new Date('1998-03-23'),
        job_id: 'SA_REP',
        salary: 10000,
        commission_pct: 0.2,
        manager_id: 148,
        department_id: 80,
      },
      {
        employee_id: 170,
        first_name: 'Tayler',
        last_name: 'Fox',
        email: 'tayler.fox@prisma.io',
        phone_number: '011.44.1343.729268',
        hire_date: new Date('1998-01-24'),
        job_id: 'SA_REP',
        salary: 9600,
        commission_pct: 0.2,
        manager_id: 148,
        department_id: 80,
      },
      {
        employee_id: 171,
        first_name: 'William',
        last_name: 'Smith',
        email: 'william.smith@prisma.io',
        phone_number: '011.44.1343.629268',
        hire_date: new Date('1999-02-23'),
        job_id: 'SA_REP',
        salary: 7400,
        commission_pct: 0.15,
        manager_id: 148,
        department_id: 80,
      },
      {
        employee_id: 172,
        first_name: 'Elizabeth',
        last_name: 'Bates',
        email: 'elizabeth.bates@prisma.io',
        phone_number: '011.44.1343.529268',
        hire_date: new Date('2000-03-24'),
        job_id: 'SA_REP',
        salary: 7300,
        commission_pct: 0.15,
        manager_id: 148,
        department_id: 80,
      },
      {
        employee_id: 173,
        first_name: 'Sundita',
        last_name: 'Kumar',
        email: 'sundita.kumar@prisma.io',
        phone_number: '011.44.1343.329268',
        hire_date: new Date('1995-08-21'),
        job_id: 'SA_REP',
        salary: 6100,
        commission_pct: 0.1,
        manager_id: 148,
        department_id: 80,
      },
      {
        employee_id: 174,
        first_name: 'Ellen',
        last_name: 'Abel',
        email: 'ellen.abel@prisma.io',
        phone_number: '011.44.1644.429267',
        hire_date: new Date('1996-05-11'),
        job_id: 'SA_REP',
        salary: 11000,
        commission_pct: 0.3,
        manager_id: 149,
        department_id: 80,
      },
      {
        employee_id: 175,
        first_name: 'Alyssa',
        last_name: 'Hutton',
        email: 'alyssa.hutton@prisma.io',
        phone_number: '011.44.1644.429266',
        hire_date: new Date('1997-03-19'),
        job_id: 'SA_REP',
        salary: 8800,
        commission_pct: 0.25,
        manager_id: 149,
        department_id: 80,
      },
      {
        employee_id: 176,
        first_name: 'Jonathon',
        last_name: 'Taylor',
        email: 'jonathon.taylor@prisma.io',
        phone_number: '011.44.1644.429265',
        hire_date: new Date('1998-03-24'),
        job_id: 'SA_REP',
        salary: 8600,
        commission_pct: 0.2,
        manager_id: 149,
        department_id: 80,
      },
      {
        employee_id: 177,
        first_name: 'Jack',
        last_name: 'Livingston',
        email: 'jack.livingston@prisma.io',
        phone_number: '011.44.1644.429264',
        hire_date: new Date('1999-04-23'),
        job_id: 'SA_REP',
        salary: 8400,
        commission_pct: 0.2,
        manager_id: 149,
        department_id: 80,
      },
      {
        employee_id: 178,
        first_name: 'Kimberely',
        last_name: 'Grant',
        email: 'kimberely.grant@prisma.io',
        phone_number: '011.44.1644.429263',
        hire_date: new Date('1999-05-24'),
        job_id: 'SA_REP',
        salary: 7000,
        commission_pct: 0.15,
        manager_id: 149,
        department_id: 80,
      },
      {
        employee_id: 179,
        first_name: 'Charles',
        last_name: 'Johnson',
        email: 'charles.johnson@prisma.io',
        phone_number: '011.44.1644.429262',
        hire_date: new Date('2000-01-04'),
        job_id: 'SA_REP',
        salary: 6200,
        commission_pct: 0.1,
        manager_id: 149,
        department_id: 80,
      },
      {
        employee_id: 180,
        first_name: 'Winston',
        last_name: 'Taylor',
        email: 'winston.taylor@prisma.io',
        phone_number: '650.507.9876',
        hire_date: new Date('1995-01-24'),
        job_id: 'SH_CLERK',
        salary: 3200,
        manager_id: 120,
        department_id: 50,
      },
      {
        employee_id: 181,
        first_name: 'Jean',
        last_name: 'Fleaur',
        email: 'jean.fleaur@prisma.io',
        phone_number: '650.507.9877',
        hire_date: new Date('1998-02-23'),
        job_id: 'SH_CLERK',
        salary: 3100,
        manager_id: 120,
        department_id: 50,
      },
      {
        employee_id: 182,
        first_name: 'Martha',
        last_name: 'Sullivan',
        email: 'martha.sullivan@prisma.io',
        phone_number: '650.507.9878',
        hire_date: new Date('1999-06-21'),
        job_id: 'SH_CLERK',
        salary: 2500,
        manager_id: 120,
        department_id: 50,
      },
      {
        employee_id: 183,
        first_name: 'Girard',
        last_name: 'Geoni',
        email: 'girard.geoni@prisma.io',
        phone_number: '650.507.9879',
        hire_date: new Date('1997-12-19'),
        job_id: 'SH_CLERK',
        salary: 2800,
        manager_id: 120,
        department_id: 50,
      },
      {
        employee_id: 184,
        first_name: 'Nandita',
        last_name: 'Sarchand',
        email: 'nandita.sarchand@prisma.io',
        phone_number: '650.509.1876',
        hire_date: new Date('1998-01-27'),
        job_id: 'SH_CLERK',
        salary: 4200,
        manager_id: 121,
        department_id: 50,
      },
      {
        employee_id: 185,
        first_name: 'Alexis',
        last_name: 'Bull',
        email: 'alexis.bull@prisma.io',
        phone_number: '650.509.2876',
        hire_date: new Date('1999-02-20'),
        job_id: 'SH_CLERK',
        salary: 4100,
        manager_id: 121,
        department_id: 50,
      },
      {
        employee_id: 186,
        first_name: 'Julia',
        last_name: 'Dellinger',
        email: 'julia.dellinger@prisma.io',
        phone_number: '650.509.3876',
        hire_date: new Date('1999-06-24'),
        job_id: 'SH_CLERK',
        salary: 3400,
        manager_id: 121,
        department_id: 50,
      },
      {
        employee_id: 187,
        first_name: 'Anthony',
        last_name: 'Cabrio',
        email: 'anthony.cabrio@prisma.io',
        phone_number: '650.509.4876',
        hire_date: new Date('2000-02-07'),
        job_id: 'SH_CLERK',
        salary: 3000,
        manager_id: 121,
        department_id: 50,
      },
      {
        employee_id: 188,
        first_name: 'Kelly',
        last_name: 'Chung',
        email: 'kelly.chung@prisma.io',
        phone_number: '650.505.1876',
        hire_date: new Date('1999-06-14'),
        job_id: 'SH_CLERK',
        salary: 3800,
        manager_id: 122,
        department_id: 50,
      },
      {
        employee_id: 189,
        first_name: 'Jennifer',
        last_name: 'Dilly',
        email: 'jennifer.dilly@prisma.io',
        phone_number: '650.505.2876',
        hire_date: new Date('1997-08-13'),
        job_id: 'SH_CLERK',
        salary: 3600,
        manager_id: 122,
        department_id: 50,
      },
      {
        employee_id: 190,
        first_name: 'Timothy',
        last_name: 'Gates',
        email: 'timothy.gates@prisma.io',
        phone_number: '650.505.3876',
        hire_date: new Date('1998-07-11'),
        job_id: 'SH_CLERK',
        salary: 2900,
        manager_id: 122,
        department_id: 50,
      },
      {
        employee_id: 191,
        first_name: 'Randall',
        last_name: 'Perkins',
        email: 'randall.perkins@prisma.io',
        phone_number: '650.505.4876',
        hire_date: new Date('1999-12-19'),
        job_id: 'SH_CLERK',
        salary: 2500,
        manager_id: 122,
        department_id: 50,
      },
      {
        employee_id: 192,
        first_name: 'Sarah',
        last_name: 'Bell',
        email: 'sarah.bell@prisma.io',
        hire_date: new Date('1996-02-04'),
        job_id: 'SH_CLERK',
        salary: 4000,
        manager_id: 123,
        department_id: 50,
      },
      {
        employee_id: 193,
        first_name: 'Britney',
        last_name: 'Everett',
        email: 'britney@prisma.io',
        hire_date: new Date('1997-03-03'),
        job_id: 'SH_CLERK',
        salary: 3900,
        manager_id: 123,
        department_id: 50,
      },
      {
        employee_id: 194,
        first_name: 'Samuel',
        last_name: 'McCain',
        email: 'samuel.mccain@prisma.io',
        hire_date: new Date('1998-07-01'),
        job_id: 'SH_CLERK',
        salary: 3200,
        manager_id: 123,
        department_id: 50,
      },
      {
        employee_id: 195,
        first_name: 'Vance',
        last_name: 'Jones',
        email: 'vance.jones@prisma.io',
        hire_date: new Date('1999-03-17'),
        job_id: 'SH_CLERK',
        salary: 2800,
        manager_id: 123,
        department_id: 50,
      },
      {
        employee_id: 196,
        first_name: 'Alana',
        last_name: 'Walsh',
        email: 'alana.walsh@prisma.io',
        hire_date: new Date('1998-04-24'),
        job_id: 'SH_CLERK',
        salary: 3100,
        manager_id: 124,
        department_id: 50,
      },
      {
        employee_id: 197,
        first_name: 'Kevin',
        last_name: 'Feeney',
        email: 'kevin.feeney@prisma.io',
        hire_date: new Date('1998-05-23'),
        job_id: 'SH_CLERK',
        salary: 3000,
        manager_id: 124,
        department_id: 50,
      },
      {
        employee_id: 198,
        first_name: 'Donald',
        last_name: 'OConnell',
        email: 'donald.oconnell@prisma.io',
        hire_date: new Date('1999-06-21'),
        job_id: 'SH_CLERK',
        salary: 2600,
        manager_id: 124,
        department_id: 50,
      },
      {
        employee_id: 199,
        first_name: 'Douglas',
        last_name: 'Grant',
        email: 'douglas.grant@prisma.io',
        hire_date: new Date('2000-01-13'),
        job_id: 'SH_CLERK',
        salary: 2600,
        manager_id: 124,
        department_id: 50,
      },
      {
        employee_id: 200,
        first_name: 'Jennifer',
        last_name: 'Whalen',
        email: 'jennifer.whalen@prisma.io',
        hire_date: new Date('1995-09-17'),
        job_id: 'AD_ASST',
        salary: 4400,
        manager_id: 101,
        department_id: 10,
      },
    ],
    skipDuplicates: true,
  });

  const jobhistories = await prisma.job_history.createMany({
    data: [
      {
        employee_id: 102,
        job_id: 'IT_PROG',
        department_id: 60,
        start_date: new Date('2001-09-17'),
        end_date: new Date('2006-12-19'),
      },
      {
        employee_id: 101,
        job_id: 'AC_ACCOUNT',
        department_id: 110,
        start_date: new Date('2001-09-21'),
        end_date: new Date('2005-12-31'),
      },
      {
        employee_id: 101,
        job_id: 'AC_MGR',
        department_id: 110,
        start_date: new Date('2006-01-01'),
        end_date: new Date('2007-12-31'),
      },
      {
        employee_id: 201,
        job_id: 'MK_REP',
        department_id: 20,
        start_date: new Date('2006-02-10'),
        end_date: new Date('2007-12-31'),
      },
      {
        employee_id: 114,
        job_id: 'ST_CLERK',
        department_id: 50,
        start_date: new Date('2007-01-01'),
        end_date: new Date('2007-12-31'),
      },
      {
        employee_id: 122,
        job_id: 'ST_CLERK',
        department_id: 50,
        start_date: new Date('2007-01-01'),
        end_date: new Date('2007-12-31'),
      },
      {
        employee_id: 200,
        job_id: 'AD_ASST',
        department_id: 90,
        start_date: new Date('2002-12-17'),
        end_date: new Date('2006-07-24'),
      },
      {
        employee_id: 176,
        job_id: 'SA_REP',
        department_id: 80,
        start_date: new Date('2006-03-24'),
        end_date: new Date('2006-12-31'),
      },
      {
        employee_id: 200,
        job_id: 'AC_ACCOUNT',
        department_id: 90,
        start_date: new Date('2007-01-01'),
        end_date: new Date('2007-12-31'),
      },
    ],
    skipDuplicates: true,
  });

  console.log({
    regions,
    countries,
    locations,
    departments,
    jobs,
    employees,
    jobhistories,
  });

  const dept10 = await prisma.departments.update({
    where: { department_id: 10 },
    data: {
      employees_departments_manager_idToemployees: {
        connect: { employee_id: 200 },
      },
    },
  });

  const dept20 = await prisma.departments.update({
    where: { department_id: 20 },
    data: {
      employees_departments_manager_idToemployees: {
        connect: { employee_id: 101 },
      },
    },
  });

  const dept30 = await prisma.departments.update({
    where: { department_id: 30 },
    data: {
      employees_departments_manager_idToemployees: {
        connect: { employee_id: 114 },
      },
    },
  });

  const dept40 = await prisma.departments.update({
    where: { department_id: 40 },
    data: {
      employees_departments_manager_idToemployees: {
        connect: { employee_id: 114 },
      },
    },
  });

  const dept50 = await prisma.departments.update({
    where: { department_id: 50 },
    data: {
      employees_departments_manager_idToemployees: {
        connect: { employee_id: 121 },
      },
    },
  });

  const dept60 = await prisma.departments.update({
    where: { department_id: 60 },
    data: {
      employees_departments_manager_idToemployees: {
        connect: { employee_id: 103 },
      },
    },
  });

  const dept70 = await prisma.departments.update({
    where: { department_id: 70 },
    data: {
      employees_departments_manager_idToemployees: {
        connect: { employee_id: 113 },
      },
    },
  });

  const dept80 = await prisma.departments.update({
    where: { department_id: 80 },
    data: {
      employees_departments_manager_idToemployees: {
        connect: { employee_id: 145 },
      },
    },
  });

  const dept90 = await prisma.departments.update({
    where: { department_id: 90 },
    data: {
      employees_departments_manager_idToemployees: {
        connect: { employee_id: 100 },
      },
    },
  });

  const dept100 = await prisma.departments.update({
    where: { department_id: 100 },
    data: {
      employees_departments_manager_idToemployees: {
        connect: { employee_id: 108 },
      },
    },
  });

  console.log({
    dept10,
    dept20,
    dept30,
    dept40,
    dept50,
    dept60,
    dept70,
    dept80,
    dept90,
    dept100,
  });
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
